name: old-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2016.9.26=py36_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libzlib=1.2.12=h166bdaf_3
  - ncurses=6.3=h27087fc_1
  - numpy=1.11.3=py36he5ce36f_1207
  - openssl=1.1.1q=h166bdaf_0
  - pandas=0.19.2=np111py36_1
  - pip=21.2.4=pyhd8ed1ab_0
  - python=3.6.15=hb7a2778_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2022.2.1=pyhd8ed1ab_0
  - readline=8.1.2=h0f457ee_0
  - setuptools=49.6.0=py36h5fab9bb_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.3=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
prefix: /home/ipozdeev/miniconda3/envs/old-env
